name: Docs Link Check

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'mkdocs-linkcheck.yml'
      - '.github/workflows/docs-linkcheck.yml'

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install MkDocs + linkcheck
        run: |
          pip install --upgrade pip
          pip install mkdocs-material==9.5.18 mkdocs-linkcheck
      - name: Link check build
        run: mkdocs build -f mkdocs-linkcheck.yml --strict --site-dir /tmp/site
      - name: Summary
        run: echo "Link check passed." >> $GITHUB_STEP_SUMMARY