name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql
          coverage: none
      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist --no-progress
      - name: Generate release notes
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          php artisan release:notes $TAG --no-heading --output=release_notes.md
          echo "Generated notes for $TAG:"; sed -n '1,80p' release_notes.md
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
